# Generated by Django 5.2.13 on 2026-05-26 10:12

from django.db import migrations, models

import crm.clients.validators


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0002_alter_client_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="company_nip",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=20,
                null=True,
                validators=[crm.clients.validators.validate_nip],
                verbose_name="NIP",
            ),
        ),
    ]
