# Generated by Django 5.2.13 on 2026-06-29 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0003_alter_client_company_nip"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="client_type",
            field=models.CharField(
                choices=[("person", "Person / FOP"), ("company", "Company / Firm")],
                default="person",
                help_text="FOP/osoba fizyczna or Firma/spółka",
                max_length=20,
                verbose_name="Client type",
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="notes",
            field=models.TextField(blank=True, verbose_name="Notes"),
        ),
    ]
