# Generated by Django 5.2.13 on 2026-06-30 08:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0003_alter_client_company_nip"),
        ("zetom", "0006_alter_oferta_company_name_alter_oferta_created_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ClientInteraction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("call", "Call"),
                            ("email", "Email"),
                            ("meeting", "Meeting"),
                            ("chat", "Chat"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                        verbose_name="Channel",
                    ),
                ),
                ("summary", models.TextField(verbose_name="Summary")),
                (
                    "contact_person",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Contact person"
                    ),
                ),
                ("contacted_at", models.DateTimeField(verbose_name="Contacted at")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interactions",
                        to="clients.client",
                        verbose_name="Client",
                    ),
                ),
                (
                    "contacted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="client_interactions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Contacted by",
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="client_interactions",
                        to="zetom.requestmain",
                        verbose_name="Request",
                    ),
                ),
            ],
            options={
                "verbose_name": "Client interaction",
                "verbose_name_plural": "Client interactions",
                "ordering": ["-contacted_at"],
            },
        ),
    ]
