# Generated by Django 5.2.13 on 2026-06-30 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0004_client_client_type_client_notes"),
        ("clients", "0004_clientinteraction"),
    ]

    operations = []
