# Generated by Django 5.2.13 on 2026-07-21 02:32

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models

import crm.clients.validators


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0005_merge_20260630_2205"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                (
                    "short_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Short name"
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Full name"
                    ),
                ),
                (
                    "nip",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=20,
                        null=True,
                        validators=[crm.clients.validators.validate_nip],
                        verbose_name="NIP",
                    ),
                ),
                (
                    "regon",
                    models.CharField(blank=True, max_length=14, verbose_name="REGON"),
                ),
                (
                    "type_supplier",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("lokalny", "Lokalny"),
                            ("regionalny", "Regionalny"),
                            ("miedzynarodowy", "Międzynarodowy"),
                        ],
                        max_length=20,
                        verbose_name="Supplier type",
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Country"
                    ),
                ),
                (
                    "city",
                    models.CharField(blank=True, max_length=100, verbose_name="City"),
                ),
                (
                    "voivodeship",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Voivodeship"
                    ),
                ),
                (
                    "post_code",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Post code"
                    ),
                ),
                (
                    "street",
                    models.CharField(blank=True, max_length=255, verbose_name="Street"),
                ),
                (
                    "phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True,
                        max_length=128,
                        null=True,
                        region=None,
                        verbose_name="Phone",
                    ),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                ("comments", models.TextField(blank=True, verbose_name="Comments")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Company",
                "verbose_name_plural": "Companies",
            },
        ),
        migrations.CreateModel(
            name="CompanyPersonLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Position"
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(default=False, verbose_name="Primary contact"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="person_links",
                        to="clients.company",
                        verbose_name="Company",
                    ),
                ),
                (
                    "linked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Linked by",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="company_links",
                        to="clients.client",
                        verbose_name="Person",
                    ),
                ),
            ],
            options={
                "verbose_name": "Company contact",
                "verbose_name_plural": "Company contacts",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("company", "person"), name="uniq_company_person"
                    )
                ],
            },
        ),
    ]
