# Generated by Django 5.2.13 on 2026-07-21 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0007_backfill_companies"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="company",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("nip__isnull", False), models.Q(("nip", ""), _negated=True)
                ),
                fields=("nip",),
                name="uniq_company_nip",
            ),
        ),
    ]
