# Generated by Django 5.2.13 on 2026-07-27 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0008_company_uniq_company_nip"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="client",
            name="client_type",
        ),
        migrations.RemoveField(
            model_name="client",
            name="company_name",
        ),
        migrations.RemoveField(
            model_name="client",
            name="company_nip",
        ),
    ]
