# Generated by Django 5.2.13 on 2026-08-24 03:18

# claude — ONE-WAY MIGRATION. Reverse is `RunPython.noop`: rolling back
# (`migrate clients 0009`) does NOT delete the StepNote rows this migration
# created, because nothing on StepNote uniquely constrains against its
# ClientInteraction source. If you roll back and then re-apply this
# migration, every ClientInteraction row is copied again, duplicating data.
# Do not re-run this migration after a reverse without manually clearing the
# StepNote rows it created first (kind="contact", created from this run).

from django.db import migrations

# claude
from crm.zetom.services.step_notes import migrate_client_interactions


def migrate_forwards(apps, schema_editor):
    ClientInteraction = apps.get_model("clients", "ClientInteraction")
    StepNote = apps.get_model("zetom", "StepNote")
    ContentType = apps.get_model("contenttypes", "ContentType")
    migrate_client_interactions(ClientInteraction, StepNote, ContentType)


class Migration(migrations.Migration):

    dependencies = [
        (
            "clients",
            "0009_remove_client_client_type_remove_client_company_name_and_more",
        ),
        ("zetom", "0017_stepnote_kind_constraints"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.RunPython(migrate_forwards, migrations.RunPython.noop),
    ]
