# Generated by Django 5.2.13 on 2026-08-24 03:18

from django.db import migrations

# claude
from crm.zetom.services.step_notes import migrate_client_interactions


def migrate_forwards(apps, schema_editor):
    ClientInteraction = apps.get_model("clients", "ClientInteraction")
    StepNote = apps.get_model("zetom", "StepNote")
    ContentType = apps.get_model("contenttypes", "ContentType")
    migrate_client_interactions(ClientInteraction, StepNote, ContentType)


class Migration(migrations.Migration):

    dependencies = [
        (
            "clients",
            "0009_remove_client_client_type_remove_client_company_name_and_more",
        ),
        ("zetom", "0017_stepnote_kind_constraints"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.RunPython(migrate_forwards, migrations.RunPython.noop),
    ]
