# Generated by Django 5.2.13 on 2026-08-24 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0010_migrate_interactions_to_step_notes"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ClientInteraction",
        ),
    ]
