# Generated by Django 5.2.15 on 2026-10-08 06:20

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0011_delete_clientinteraction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=128, null=True, region=None, verbose_name="Phone"
            ),
        ),
    ]
