# Generated by Django 5.2.15 on 2026-09-20 10:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("status_manager", "0001_initial"),
        ("zetom", "0018_document_chain"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChildDocumentDeletion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("document_type", models.CharField(max_length=20)),
                ("document_repr", models.CharField(max_length=255)),
                ("reason", models.TextField(blank=True)),
                ("deleted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "deleted_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "from_main",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="child_document_deletions",
                        to="zetom.requestmain",
                    ),
                ),
            ],
            options={
                "ordering": ["-deleted_at"],
            },
        ),
    ]
