# Generated by Django 5.2.15 on 2026-10-08 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("status_manager", "0002_childdocumentdeletion"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="childdocumentdeletion",
            options={
                "ordering": ["-deleted_at"],
                "verbose_name": "Child document deletion",
                "verbose_name_plural": "Child document deletions",
            },
        ),
        migrations.AlterModelOptions(
            name="statushistory",
            options={
                "ordering": ["-changed_at"],
                "verbose_name": "Status history entry",
                "verbose_name_plural": "Status history",
            },
        ),
    ]
