# Generated by Django 5.2.13 on 2026-04-16 09:23

import django.core.validators
import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RequestMain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None
                    ),
                ),
                (
                    "company_name",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("email", models.EmailField(max_length=100)),
                (
                    "company_nip",
                    models.CharField(
                        max_length=10,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Your NIP sucks man, It must be 10 digits yo",
                                regex="^\\d{10}$",
                            )
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("full_name", models.CharField(blank=True, max_length=50, null=True)),
                ("address", models.CharField(blank=True, max_length=50, null=True)),
                ("notes", models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                "verbose_name": "Information",
                "verbose_name_plural": "Information",
            },
        ),
        migrations.CreateModel(
            name="RequestNull",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None
                    ),
                ),
                (
                    "company_name",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("email", models.EmailField(max_length=100)),
                (
                    "company_nip",
                    models.CharField(
                        max_length=10,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Your NIP sucks man, It must be 10 digits yo",
                                regex="^\\d{10}$",
                            )
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Validation Window",
                "verbose_name_plural": "Validation Window",
            },
        ),
        migrations.CreateModel(
            name="Oferta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None
                    ),
                ),
                (
                    "company_name",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("email", models.EmailField(max_length=100)),
                (
                    "company_nip",
                    models.CharField(
                        max_length=10,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Your NIP sucks man, It must be 10 digits yo",
                                regex="^\\d{10}$",
                            )
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "from_main",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="zetom.requestmain",
                    ),
                ),
            ],
            options={
                "verbose_name": "Oferta Information",
                "verbose_name_plural": "Oferta Information",
            },
        ),
        migrations.AddField(
            model_name="requestmain",
            name="from_null",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="zetom.requestnull",
            ),
        ),
    ]
