# Generated by Django 5.2.13 on 2026-04-15 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zetom", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="oferta",
            options={
                "verbose_name": "Oferta Information",
                "verbose_name_plural": "Oferta Information",
            },
        ),
        migrations.AlterModelOptions(
            name="requestmain",
            options={
                "verbose_name": "Information",
                "verbose_name_plural": "Information",
            },
        ),
        migrations.AlterModelOptions(
            name="requestnull",
            options={
                "verbose_name": "Validation Window",
                "verbose_name_plural": "Validation Window",
            },
        ),
        migrations.AlterModelOptions(
            name="role",
            options={"verbose_name": "Roles", "verbose_name_plural": "Roles"},
        ),
        migrations.AlterModelOptions(
            name="userprofile",
            options={"verbose_name": "Users", "verbose_name_plural": "Users"},
        ),
        migrations.AddField(
            model_name="oferta",
            name="deleted",
            field=models.DateTimeField(db_index=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="oferta",
            name="deleted_by_cascade",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="requestmain",
            name="deleted",
            field=models.DateTimeField(db_index=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="requestmain",
            name="deleted_by_cascade",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="requestnull",
            name="deleted",
            field=models.DateTimeField(db_index=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="requestnull",
            name="deleted_by_cascade",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name="oferta",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name="requestmain",
            name="address",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="requestmain",
            name="notes",
            field=models.CharField(max_length=500, null=True),
        ),
    ]
