# Generated by Django 5.2.13 on 2026-04-14 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zetom", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="oferta",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name="requestmain",
            name="address",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="requestmain",
            name="notes",
            field=models.CharField(max_length=500, null=True),
        ),
    ]
