# Generated by Django 5.2.13 on 2026-04-21 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zetom", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="oferta",
            name="status",
            field=models.CharField(default="new", max_length=20),
        ),
        migrations.AddField(
            model_name="requestmain",
            name="is_archived",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="requestmain",
            name="status",
            field=models.CharField(default="new", max_length=20),
        ),
    ]
