# Generated by Django 5.2.13 on 2026-04-15 16:43

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zetom", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="oferta",
            options={
                "verbose_name": "Oferta Information",
                "verbose_name_plural": "Oferta Information",
            },
        ),
        migrations.AlterModelOptions(
            name="requestmain",
            options={
                "verbose_name": "Information",
                "verbose_name_plural": "Information",
            },
        ),
        migrations.AlterModelOptions(
            name="requestnull",
            options={
                "verbose_name": "Validation Window",
                "verbose_name_plural": "Validation Window",
            },
        ),
        migrations.AlterModelOptions(
            name="role",
            options={"verbose_name": "Roles", "verbose_name_plural": "Roles"},
        ),
        migrations.AlterModelOptions(
            name="userprofile",
            options={"verbose_name": "Users", "verbose_name_plural": "Users"},
        ),
        migrations.AddField(
            model_name="oferta",
            name="deleted",
            field=models.DateTimeField(db_index=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="oferta",
            name="deleted_by_cascade",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="requestmain",
            name="deleted",
            field=models.DateTimeField(db_index=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="requestmain",
            name="deleted_by_cascade",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="requestnull",
            name="deleted",
            field=models.DateTimeField(db_index=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="requestnull",
            name="deleted_by_cascade",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name="oferta",
            name="company_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="oferta",
            name="company_nip",
            field=models.CharField(
                max_length=10,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Your NIP sucks man, It must be 10 digits yo",
                        regex="^\\d{10}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="oferta",
            name="from_main",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="zetom.requestmain",
            ),
        ),
        migrations.AlterField(
            model_name="oferta",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="requestmain",
            name="address",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="requestmain",
            name="company_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="requestmain",
            name="company_nip",
            field=models.CharField(
                max_length=10,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Your NIP sucks man, It must be 10 digits yo",
                        regex="^\\d{10}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="requestmain",
            name="from_null",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="zetom.requestnull",
            ),
        ),
        migrations.AlterField(
            model_name="requestmain",
            name="full_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="requestmain",
            name="notes",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="requestnull",
            name="company_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="requestnull",
            name="company_nip",
            field=models.CharField(
                max_length=10,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Your NIP sucks man, It must be 10 digits yo",
                        regex="^\\d{10}$",
                    )
                ],
            ),
        ),
    ]
