# Generated by Django 5.2.13 on 2026-04-15 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zetom", "0002_alter_oferta_price_alter_requestmain_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="oferta",
            name="deleted",
            field=models.DateTimeField(db_index=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="oferta",
            name="deleted_by_cascade",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="requestmain",
            name="deleted",
            field=models.DateTimeField(db_index=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="requestmain",
            name="deleted_by_cascade",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="requestnull",
            name="deleted",
            field=models.DateTimeField(db_index=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="requestnull",
            name="deleted_by_cascade",
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
