# Generated by Django 5.2.13 on 2026-04-21 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zetom", "0002_oferta_status_requestmain_is_archived_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="oferta",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "Новый"),
                    ("in_progress", "В работе"),
                    ("waiting", "Ожидание"),
                    ("done", "Выполнено"),
                ],
                default="new",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="requestmain",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "Новый"),
                    ("in_progress", "В работе"),
                    ("waiting", "Ожидание"),
                    ("done", "Выполнено"),
                ],
                default="new",
                max_length=20,
            ),
        ),
    ]
