# Generated by Django 5.2.13 on 2026-04-24 20:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zetom", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="oferta",
            name="company_nip",
            field=models.CharField(
                max_length=10,
                validators=[django.core.validators.RegexValidator(regex="^\\d{10}$")],
            ),
        ),
        migrations.AlterField(
            model_name="requestmain",
            name="company_nip",
            field=models.CharField(
                max_length=10,
                validators=[django.core.validators.RegexValidator(regex="^\\d{10}$")],
            ),
        ),
        migrations.AlterField(
            model_name="requestnull",
            name="company_nip",
            field=models.CharField(
                max_length=10,
                validators=[django.core.validators.RegexValidator(regex="^\\d{10}$")],
            ),
        ),
        migrations.AlterField(
            model_name="wniosek",
            name="company_nip",
            field=models.CharField(
                max_length=10,
                validators=[django.core.validators.RegexValidator(regex="^\\d{10}$")],
            ),
        ),
        migrations.AlterField(
            model_name="zlecenie",
            name="company_nip",
            field=models.CharField(
                max_length=10,
                validators=[django.core.validators.RegexValidator(regex="^\\d{10}$")],
            ),
        ),
    ]
