# Generated by Django 5.2.13 on 2026-04-22 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zetom", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="requestmain",
            name="notes",
        ),
        migrations.AddField(
            model_name="oferta",
            name="message",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="oferta",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="requestmain",
            name="message",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="requestnull",
            name="message",
            field=models.TextField(blank=True, null=True),
        ),
    ]
