# Generated by Django 5.2.13 on 2026-05-09 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("zetom", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CancelledRequest",
            fields=[],
            options={
                "verbose_name": "Cancelled Request",
                "verbose_name_plural": "Cancelled Requests",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("zetom.requestmain",),
        ),
    ]
