# Generated by Django 5.2.13 on 2026-04-22 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zetom", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="requestmain",
            name="notes",
        ),
        migrations.AddField(
            model_name="oferta",
            name="department",
            field=models.CharField(
                blank=True,
                choices=[
                    ("DEPARTMENT_0", "department 1"),
                    ("DEPARTMENT_1", "department 2"),
                    ("DEPARTMENT_2", "department 3"),
                    ("DEPARTMENT_3", "department 4"),
                ],
                default="DEPARTMENT_0",
                max_length=30,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="oferta",
            name="message",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="oferta",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="oferta",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "New"),
                    ("in_progress", "In Progress"),
                    ("waiting", "Waiting"),
                    ("done", "Done"),
                ],
                default="new",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="oferta",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="requestmain",
            name="department",
            field=models.CharField(
                blank=True,
                choices=[
                    ("DEPARTMENT_0", "department 1"),
                    ("DEPARTMENT_1", "department 2"),
                    ("DEPARTMENT_2", "department 3"),
                    ("DEPARTMENT_3", "department 4"),
                ],
                default="DEPARTMENT_0",
                max_length=30,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="requestmain",
            name="is_archived",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="requestmain",
            name="message",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="requestmain",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "New"),
                    ("in_progress", "In Progress"),
                    ("waiting", "Waiting"),
                    ("done", "Done"),
                ],
                default="new",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="requestmain",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="requestnull",
            name="department",
            field=models.CharField(
                blank=True,
                choices=[
                    ("DEPARTMENT_0", "department 1"),
                    ("DEPARTMENT_1", "department 2"),
                    ("DEPARTMENT_2", "department 3"),
                    ("DEPARTMENT_3", "department 4"),
                ],
                default="DEPARTMENT_0",
                max_length=30,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="requestnull",
            name="message",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="requestnull",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="requestmain",
            name="address",
            field=models.CharField(blank=True, max_length=228, null=True),
        ),
    ]
