# Generated by Django 5.2.13 on 2026-04-24 12:38

import django.core.validators
import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zetom", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="requestmain",
            name="notes",
        ),
        migrations.AddField(
            model_name="oferta",
            name="department",
            field=models.CharField(
                blank=True,
                choices=[
                    ("DEPARTMENT_0", "department 1"),
                    ("DEPARTMENT_1", "department 2"),
                    ("DEPARTMENT_2", "department 3"),
                    ("DEPARTMENT_3", "department 4"),
                ],
                default="DEPARTMENT_0",
                max_length=30,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="oferta",
            name="message",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="oferta",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="oferta",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "New"),
                    ("in_progress", "In Progress"),
                    ("waiting", "Waiting"),
                    ("done", "Done"),
                ],
                default="new",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="oferta",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="requestmain",
            name="department",
            field=models.CharField(
                blank=True,
                choices=[
                    ("DEPARTMENT_0", "department 1"),
                    ("DEPARTMENT_1", "department 2"),
                    ("DEPARTMENT_2", "department 3"),
                    ("DEPARTMENT_3", "department 4"),
                ],
                default="DEPARTMENT_0",
                max_length=30,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="requestmain",
            name="is_archived",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="requestmain",
            name="message",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="requestmain",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "New"),
                    ("in_progress", "In Progress"),
                    ("waiting", "Waiting"),
                    ("done", "Done"),
                ],
                default="new",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="requestmain",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="requestnull",
            name="department",
            field=models.CharField(
                blank=True,
                choices=[
                    ("DEPARTMENT_0", "department 1"),
                    ("DEPARTMENT_1", "department 2"),
                    ("DEPARTMENT_2", "department 3"),
                    ("DEPARTMENT_3", "department 4"),
                ],
                default="DEPARTMENT_0",
                max_length=30,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="requestnull",
            name="message",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="requestnull",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="oferta",
            name="company_nip",
            field=models.CharField(
                max_length=10,
                validators=[django.core.validators.RegexValidator(regex="^\\d{10}$")],
            ),
        ),
        migrations.AlterField(
            model_name="requestmain",
            name="address",
            field=models.CharField(blank=True, max_length=228, null=True),
        ),
        migrations.AlterField(
            model_name="requestmain",
            name="company_nip",
            field=models.CharField(
                max_length=10,
                validators=[django.core.validators.RegexValidator(regex="^\\d{10}$")],
            ),
        ),
        migrations.AlterField(
            model_name="requestnull",
            name="company_nip",
            field=models.CharField(
                max_length=10,
                validators=[django.core.validators.RegexValidator(regex="^\\d{10}$")],
            ),
        ),
        migrations.CreateModel(
            name="Wniosek",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None
                    ),
                ),
                (
                    "company_name",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("email", models.EmailField(max_length=100)),
                (
                    "company_nip",
                    models.CharField(
                        max_length=10,
                        validators=[
                            django.core.validators.RegexValidator(regex="^\\d{10}$")
                        ],
                    ),
                ),
                ("message", models.TextField(blank=True, null=True)),
                (
                    "department",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("DEPARTMENT_0", "department 1"),
                            ("DEPARTMENT_1", "department 2"),
                            ("DEPARTMENT_2", "department 3"),
                            ("DEPARTMENT_3", "department 4"),
                        ],
                        default="DEPARTMENT_0",
                        max_length=30,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("in_progress", "In Progress"),
                            ("waiting", "Waiting"),
                            ("done", "Done"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "application_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "from_main",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="zetom.requestmain",
                    ),
                ),
            ],
            options={
                "verbose_name": "Wniosek Information",
                "verbose_name_plural": "Wniosek Information",
            },
        ),
        migrations.CreateModel(
            name="Zlecenie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None
                    ),
                ),
                (
                    "company_name",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("email", models.EmailField(max_length=100)),
                (
                    "company_nip",
                    models.CharField(
                        max_length=10,
                        validators=[
                            django.core.validators.RegexValidator(regex="^\\d{10}$")
                        ],
                    ),
                ),
                ("message", models.TextField(blank=True, null=True)),
                (
                    "department",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("DEPARTMENT_0", "department 1"),
                            ("DEPARTMENT_1", "department 2"),
                            ("DEPARTMENT_2", "department 3"),
                            ("DEPARTMENT_3", "department 4"),
                        ],
                        default="DEPARTMENT_0",
                        max_length=30,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("in_progress", "In Progress"),
                            ("waiting", "Waiting"),
                            ("done", "Done"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("deadline", models.DateField(blank=True, null=True)),
                (
                    "from_main",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="zetom.requestmain",
                    ),
                ),
            ],
            options={
                "verbose_name": "Zlecenie Information",
                "verbose_name_plural": "Zlecenie Information",
            },
        ),
    ]
