# Generated by Django 5.2.13 on 2026-05-25 19:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zetom", "0002_cancelledrequest"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="requestmain",
            name="owners",
            field=models.ManyToManyField(
                blank=True, related_name="owned_requests", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
