# Generated by Django 5.2.13 on 2026-04-22 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zetom", "0002_remove_requestmain_notes_oferta_message_oferta_notes_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="requestmain",
            name="address",
            field=models.CharField(blank=True, max_length=228, null=True),
        ),
    ]
