# Generated by Django 5.2.13 on 2026-05-26 10:12

from django.db import migrations, models

import crm.clients.validators


class Migration(migrations.Migration):

    dependencies = [
        ("zetom", "0003_requestmain_owners"),
    ]

    operations = [
        migrations.AlterField(
            model_name="oferta",
            name="company_nip",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                validators=[crm.clients.validators.validate_nip],
            ),
        ),
        migrations.AlterField(
            model_name="requestmain",
            name="company_nip",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                validators=[crm.clients.validators.validate_nip],
            ),
        ),
        migrations.AlterField(
            model_name="requestnull",
            name="company_nip",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                validators=[crm.clients.validators.validate_nip],
            ),
        ),
        migrations.AlterField(
            model_name="wniosek",
            name="company_nip",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                validators=[crm.clients.validators.validate_nip],
            ),
        ),
        migrations.AlterField(
            model_name="zlecenie",
            name="company_nip",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                validators=[crm.clients.validators.validate_nip],
            ),
        ),
    ]
