# Generated by Django 5.2.13 on 2026-05-04 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zetom", "0003_oferta_assigned_to_requestmain_assigned_to_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="requestmain",
            name="is_archived",
        ),
        migrations.AlterField(
            model_name="oferta",
            name="department",
            field=models.CharField(
                blank=True,
                choices=[
                    ("DEPARTMENT_0", "Zespół ds. Badań"),
                    ("DEPARTMENT_1", "Zespół ds. Wzorcowań"),
                    ("DEPARTMENT_2", "Pracownia Długości i Kąta"),
                    ("DEPARTMENT_3", "Pracownia Elektrotechniczna"),
                    ("DEPARTMENT_4", "Pracownia Mechaniczna"),
                    ("DEPARTMENT_5", "Pracownia Urządzeń Grzewczych"),
                    ("DEPARTMENT_6", "Biuro Techniczne"),
                ],
                default="DEPARTMENT_0",
                max_length=30,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="requestmain",
            name="department",
            field=models.CharField(
                blank=True,
                choices=[
                    ("DEPARTMENT_0", "Zespół ds. Badań"),
                    ("DEPARTMENT_1", "Zespół ds. Wzorcowań"),
                    ("DEPARTMENT_2", "Pracownia Długości i Kąta"),
                    ("DEPARTMENT_3", "Pracownia Elektrotechniczna"),
                    ("DEPARTMENT_4", "Pracownia Mechaniczna"),
                    ("DEPARTMENT_5", "Pracownia Urządzeń Grzewczych"),
                    ("DEPARTMENT_6", "Biuro Techniczne"),
                ],
                default="DEPARTMENT_0",
                max_length=30,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="requestmain",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("open", "Open"),
                    ("closed", "Closed"),
                    ("inactive", "Inactive"),
                    ("cancelled", "Cancelled"),
                    ("deleted", "Deleted"),
                ],
                default="active",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="requestnull",
            name="department",
            field=models.CharField(
                blank=True,
                choices=[
                    ("DEPARTMENT_0", "Zespół ds. Badań"),
                    ("DEPARTMENT_1", "Zespół ds. Wzorcowań"),
                    ("DEPARTMENT_2", "Pracownia Długości i Kąta"),
                    ("DEPARTMENT_3", "Pracownia Elektrotechniczna"),
                    ("DEPARTMENT_4", "Pracownia Mechaniczna"),
                    ("DEPARTMENT_5", "Pracownia Urządzeń Grzewczych"),
                    ("DEPARTMENT_6", "Biuro Techniczne"),
                ],
                default="DEPARTMENT_0",
                max_length=30,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="wniosek",
            name="department",
            field=models.CharField(
                blank=True,
                choices=[
                    ("DEPARTMENT_0", "Zespół ds. Badań"),
                    ("DEPARTMENT_1", "Zespół ds. Wzorcowań"),
                    ("DEPARTMENT_2", "Pracownia Długości i Kąta"),
                    ("DEPARTMENT_3", "Pracownia Elektrotechniczna"),
                    ("DEPARTMENT_4", "Pracownia Mechaniczna"),
                    ("DEPARTMENT_5", "Pracownia Urządzeń Grzewczych"),
                    ("DEPARTMENT_6", "Biuro Techniczne"),
                ],
                default="DEPARTMENT_0",
                max_length=30,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="zlecenie",
            name="department",
            field=models.CharField(
                blank=True,
                choices=[
                    ("DEPARTMENT_0", "Zespół ds. Badań"),
                    ("DEPARTMENT_1", "Zespół ds. Wzorcowań"),
                    ("DEPARTMENT_2", "Pracownia Długości i Kąta"),
                    ("DEPARTMENT_3", "Pracownia Elektrotechniczna"),
                    ("DEPARTMENT_4", "Pracownia Mechaniczna"),
                    ("DEPARTMENT_5", "Pracownia Urządzeń Grzewczych"),
                    ("DEPARTMENT_6", "Biuro Techniczne"),
                ],
                default="DEPARTMENT_0",
                max_length=30,
                null=True,
            ),
        ),
    ]
