# Generated by Django 5.2.13 on 2026-05-05 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zetom", "0003_oferta_assigned_to_requestmain_assigned_to_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="requestmain",
            name="is_archived",
        ),
        migrations.AlterField(
            model_name="requestmain",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("open", "Open"),
                    ("closed", "Closed"),
                    ("inactive", "Inactive"),
                    ("cancelled", "Cancelled"),
                    ("deleted", "Deleted"),
                ],
                default="active",
                max_length=20,
            ),
        ),
    ]
