# Generated by Django 5.2.13 on 2026-04-22 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zetom", "0003_alter_requestmain_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="oferta",
            name="department",
            field=models.CharField(
                blank=True,
                choices=[
                    ("DEPARTMENT_0", "department 1"),
                    ("DEPARTMENT_1", "department 2"),
                    ("DEPARTMENT_2", "department 3"),
                    ("DEPARTMENT_3", "department 4"),
                ],
                default="DEPARTMENT_0",
                max_length=30,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="oferta",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="requestmain",
            name="department",
            field=models.CharField(
                blank=True,
                choices=[
                    ("DEPARTMENT_0", "department 1"),
                    ("DEPARTMENT_1", "department 2"),
                    ("DEPARTMENT_2", "department 3"),
                    ("DEPARTMENT_3", "department 4"),
                ],
                default="DEPARTMENT_0",
                max_length=30,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="requestmain",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="requestnull",
            name="department",
            field=models.CharField(
                blank=True,
                choices=[
                    ("DEPARTMENT_0", "department 1"),
                    ("DEPARTMENT_1", "department 2"),
                    ("DEPARTMENT_2", "department 3"),
                    ("DEPARTMENT_3", "department 4"),
                ],
                default="DEPARTMENT_0",
                max_length=30,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="requestnull",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
