# Generated by Django 5.2.13 on 2026-05-05 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("zetom", "0004_remove_requestmain_is_archived_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeletedRequest",
            fields=[],
            options={
                "verbose_name": "Deleted Request",
                "verbose_name_plural": "Deleted Requests",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("zetom.requestmain",),
        ),
    ]
