# Generated by Django 5.2.13 on 2026-05-07 10:45 — manually edited to
# preserve existing department values: AddField -> RunPython -> RemoveField.

import django.contrib.postgres.fields
from django.db import migrations, models

DEPARTMENT_CHOICES = [
    ("DEPARTMENT_0", "Zespół ds. Badań"),
    ("DEPARTMENT_1", "Zespół ds. Wzorcowań"),
    ("DEPARTMENT_2", "Pracownia Długości i Kąta"),
    ("DEPARTMENT_3", "Pracownia Elektrotechniczna"),
    ("DEPARTMENT_4", "Pracownia Mechaniczna"),
    ("DEPARTMENT_5", "Pracownia Urządzeń Grzewczych"),
    ("DEPARTMENT_6", "Biuro Techniczne"),
]

MODELS = ["RequestNull", "RequestMain", "Oferta", "Zlecenie", "Wniosek"]


def copy_department_to_array(apps, schema_editor):
    for model_name in MODELS:
        Model = apps.get_model("zetom", model_name)
        for obj in Model.objects.all():
            if obj.department:
                obj.departments = [obj.department]
            else:
                obj.departments = []
            obj.save(update_fields=["departments"])


def copy_array_to_department(apps, schema_editor):
    for model_name in MODELS:
        Model = apps.get_model("zetom", model_name)
        for obj in Model.objects.all():
            obj.department = obj.departments[0] if obj.departments else None
            obj.save(update_fields=["department"])


def make_array_field():
    return django.contrib.postgres.fields.ArrayField(
        base_field=models.CharField(choices=DEPARTMENT_CHOICES, max_length=30),
        blank=True,
        default=list,
        size=None,
    )


class Migration(migrations.Migration):

    dependencies = [
        ("zetom", "0004_deletedrequest_remove_requestmain_is_archived_and_more"),
    ]

    operations = [
        migrations.AddField(model_name="oferta", name="departments", field=make_array_field()),
        migrations.AddField(model_name="requestmain", name="departments", field=make_array_field()),
        migrations.AddField(model_name="requestnull", name="departments", field=make_array_field()),
        migrations.AddField(model_name="wniosek", name="departments", field=make_array_field()),
        migrations.AddField(model_name="zlecenie", name="departments", field=make_array_field()),

        migrations.RunPython(copy_department_to_array, reverse_code=copy_array_to_department),

        migrations.RemoveField(model_name="oferta", name="department"),
        migrations.RemoveField(model_name="requestmain", name="department"),
        migrations.RemoveField(model_name="requestnull", name="department"),
        migrations.RemoveField(model_name="wniosek", name="department"),
        migrations.RemoveField(model_name="zlecenie", name="department"),
    ]
