# Generated by Django 5.2.13 on 2026-06-09 06:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0003_alter_client_company_nip"),
        ("zetom", "0004_alter_oferta_company_nip_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RequestClientLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("linked_at", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="request_links",
                        to="clients.client",
                    ),
                ),
                (
                    "linked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="client_links",
                        to="zetom.requestmain",
                    ),
                ),
            ],
            options={
                "verbose_name": "Client link",
                "verbose_name_plural": "Client links",
            },
        ),
        migrations.AddField(
            model_name="requestmain",
            name="clients",
            field=models.ManyToManyField(
                blank=True,
                related_name="requests",
                through="zetom.RequestClientLink",
                to="clients.client",
            ),
        ),
        migrations.AddConstraint(
            model_name="requestclientlink",
            constraint=models.UniqueConstraint(
                fields=("request", "client"), name="uniq_request_client"
            ),
        ),
    ]
