# Generated by Django 5.2.13 on 2026-05-08 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zetom", "0005_remove_oferta_department_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="oferta",
            name="source",
            field=models.CharField(
                choices=[
                    ("phone", "Phone"),
                    ("email", "Email"),
                    ("site", "Site"),
                    ("main", "Parent"),
                    ("manual", "Manual"),
                    ("other", "Other"),
                ],
                default="other",
            ),
        ),
        migrations.AddField(
            model_name="requestmain",
            name="source",
            field=models.CharField(
                choices=[
                    ("phone", "Phone"),
                    ("email", "Email"),
                    ("site", "Site"),
                    ("main", "Parent"),
                    ("manual", "Manual"),
                    ("other", "Other"),
                ],
                default="other",
            ),
        ),
        migrations.AddField(
            model_name="requestnull",
            name="source",
            field=models.CharField(
                choices=[
                    ("phone", "Phone"),
                    ("email", "Email"),
                    ("site", "Site"),
                    ("main", "Parent"),
                    ("manual", "Manual"),
                    ("other", "Other"),
                ],
                default="other",
            ),
        ),
        migrations.AddField(
            model_name="wniosek",
            name="source",
            field=models.CharField(
                choices=[
                    ("phone", "Phone"),
                    ("email", "Email"),
                    ("site", "Site"),
                    ("main", "Parent"),
                    ("manual", "Manual"),
                    ("other", "Other"),
                ],
                default="other",
            ),
        ),
        migrations.AddField(
            model_name="zlecenie",
            name="source",
            field=models.CharField(
                choices=[
                    ("phone", "Phone"),
                    ("email", "Email"),
                    ("site", "Site"),
                    ("main", "Parent"),
                    ("manual", "Manual"),
                    ("other", "Other"),
                ],
                default="other",
            ),
        ),
    ]
