# Generated by Django 5.2.13 on 2026-06-30 08:35

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0004_client_client_type_client_notes"),
        ("zetom", "0005_requestclientlink_requestmain_clients_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="oferta",
            name="company_name",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Company name"
            ),
        ),
        migrations.AlterField(
            model_name="oferta",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
        ),
        migrations.AlterField(
            model_name="oferta",
            name="email",
            field=models.EmailField(max_length=100, verbose_name="Email"),
        ),
        migrations.AlterField(
            model_name="oferta",
            name="from_main",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="zetom.requestmain",
                verbose_name="From main",
            ),
        ),
        migrations.AlterField(
            model_name="oferta",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=128, region=None, verbose_name="Phone"
            ),
        ),
        migrations.AlterField(
            model_name="oferta",
            name="source",
            field=models.CharField(
                choices=[
                    ("phone", "Phone"),
                    ("email", "Email"),
                    ("site", "Site"),
                    ("main", "Parent"),
                    ("manual", "Manual"),
                    ("other", "Other"),
                ],
                default="other",
                verbose_name="Source",
            ),
        ),
        migrations.AlterField(
            model_name="oferta",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated at"),
        ),
        migrations.AlterField(
            model_name="requestmain",
            name="company_name",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Company name"
            ),
        ),
        migrations.AlterField(
            model_name="requestmain",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
        ),
        migrations.AlterField(
            model_name="requestmain",
            name="email",
            field=models.EmailField(max_length=100, verbose_name="Email"),
        ),
        migrations.AlterField(
            model_name="requestmain",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=128, region=None, verbose_name="Phone"
            ),
        ),
        migrations.AlterField(
            model_name="requestmain",
            name="source",
            field=models.CharField(
                choices=[
                    ("phone", "Phone"),
                    ("email", "Email"),
                    ("site", "Site"),
                    ("main", "Parent"),
                    ("manual", "Manual"),
                    ("other", "Other"),
                ],
                default="other",
                verbose_name="Source",
            ),
        ),
        migrations.AlterField(
            model_name="requestmain",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated at"),
        ),
        migrations.AlterField(
            model_name="requestnull",
            name="company_name",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Company name"
            ),
        ),
        migrations.AlterField(
            model_name="requestnull",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
        ),
        migrations.AlterField(
            model_name="requestnull",
            name="email",
            field=models.EmailField(max_length=100, verbose_name="Email"),
        ),
        migrations.AlterField(
            model_name="requestnull",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=128, region=None, verbose_name="Phone"
            ),
        ),
        migrations.AlterField(
            model_name="requestnull",
            name="source",
            field=models.CharField(
                choices=[
                    ("phone", "Phone"),
                    ("email", "Email"),
                    ("site", "Site"),
                    ("main", "Parent"),
                    ("manual", "Manual"),
                    ("other", "Other"),
                ],
                default="other",
                verbose_name="Source",
            ),
        ),
        migrations.AlterField(
            model_name="requestnull",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated at"),
        ),
        migrations.AlterField(
            model_name="wniosek",
            name="company_name",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Company name"
            ),
        ),
        migrations.AlterField(
            model_name="wniosek",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
        ),
        migrations.AlterField(
            model_name="wniosek",
            name="email",
            field=models.EmailField(max_length=100, verbose_name="Email"),
        ),
        migrations.AlterField(
            model_name="wniosek",
            name="from_main",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="zetom.requestmain",
                verbose_name="From main",
            ),
        ),
        migrations.AlterField(
            model_name="wniosek",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=128, region=None, verbose_name="Phone"
            ),
        ),
        migrations.AlterField(
            model_name="wniosek",
            name="source",
            field=models.CharField(
                choices=[
                    ("phone", "Phone"),
                    ("email", "Email"),
                    ("site", "Site"),
                    ("main", "Parent"),
                    ("manual", "Manual"),
                    ("other", "Other"),
                ],
                default="other",
                verbose_name="Source",
            ),
        ),
        migrations.AlterField(
            model_name="wniosek",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated at"),
        ),
        migrations.AlterField(
            model_name="zlecenie",
            name="company_name",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Company name"
            ),
        ),
        migrations.AlterField(
            model_name="zlecenie",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
        ),
        migrations.AlterField(
            model_name="zlecenie",
            name="email",
            field=models.EmailField(max_length=100, verbose_name="Email"),
        ),
        migrations.AlterField(
            model_name="zlecenie",
            name="from_main",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="zetom.requestmain",
                verbose_name="From main",
            ),
        ),
        migrations.AlterField(
            model_name="zlecenie",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=128, region=None, verbose_name="Phone"
            ),
        ),
        migrations.AlterField(
            model_name="zlecenie",
            name="source",
            field=models.CharField(
                choices=[
                    ("phone", "Phone"),
                    ("email", "Email"),
                    ("site", "Site"),
                    ("main", "Parent"),
                    ("manual", "Manual"),
                    ("other", "Other"),
                ],
                default="other",
                verbose_name="Source",
            ),
        ),
        migrations.AlterField(
            model_name="zlecenie",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated at"),
        ),
        migrations.CreateModel(
            name="OfertaClientLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("linked_at", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="oferta_links",
                        to="clients.client",
                    ),
                ),
                (
                    "linked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="client_links",
                        to="zetom.oferta",
                    ),
                ),
            ],
            options={
                "verbose_name": "Oferta client link",
                "verbose_name_plural": "Oferta client links",
            },
        ),
        migrations.AddField(
            model_name="oferta",
            name="clients",
            field=models.ManyToManyField(
                blank=True,
                related_name="ofertas",
                through="zetom.OfertaClientLink",
                to="clients.client",
            ),
        ),
        migrations.CreateModel(
            name="WniosekClientLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("linked_at", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wniosek_links",
                        to="clients.client",
                    ),
                ),
                (
                    "linked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="client_links",
                        to="zetom.wniosek",
                    ),
                ),
            ],
            options={
                "verbose_name": "Wniosek client link",
                "verbose_name_plural": "Wniosek client links",
            },
        ),
        migrations.AddField(
            model_name="wniosek",
            name="clients",
            field=models.ManyToManyField(
                blank=True,
                related_name="wnioski",
                through="zetom.WniosekClientLink",
                to="clients.client",
            ),
        ),
        migrations.CreateModel(
            name="ZlecenieClientLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("linked_at", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="zlecenie_links",
                        to="clients.client",
                    ),
                ),
                (
                    "linked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="client_links",
                        to="zetom.zlecenie",
                    ),
                ),
            ],
            options={
                "verbose_name": "Zlecenie client link",
                "verbose_name_plural": "Zlecenie client links",
            },
        ),
        migrations.AddField(
            model_name="zlecenie",
            name="clients",
            field=models.ManyToManyField(
                blank=True,
                related_name="zlecenia",
                through="zetom.ZlecenieClientLink",
                to="clients.client",
            ),
        ),
        migrations.AddConstraint(
            model_name="ofertaclientlink",
            constraint=models.UniqueConstraint(
                fields=("request", "client"), name="uniq_oferta_client"
            ),
        ),
        migrations.AddConstraint(
            model_name="wniosekclientlink",
            constraint=models.UniqueConstraint(
                fields=("request", "client"), name="uniq_wniosek_client"
            ),
        ),
        migrations.AddConstraint(
            model_name="zlecenieclientlink",
            constraint=models.UniqueConstraint(
                fields=("request", "client"), name="uniq_zlecenie_client"
            ),
        ),
    ]
