# Generated by Django 5.2.13 on 2026-05-08 15:55 — manually edited:
# AddField first/last -> RunPython (split full_name) -> RemoveField full_name.

import django.core.validators
from django.db import migrations, models


def split_full_name(apps, schema_editor):
    RequestMain = apps.get_model("zetom", "RequestMain")
    for obj in RequestMain.objects.all():
        full = (obj.full_name or "").strip()
        if not full:
            continue
        parts = full.split(maxsplit=1)
        obj.first_name = parts[0]
        obj.last_name = parts[1] if len(parts) > 1 else ""
        obj.save(update_fields=["first_name", "last_name"])


def join_first_last(apps, schema_editor):
    RequestMain = apps.get_model("zetom", "RequestMain")
    for obj in RequestMain.objects.all():
        joined = " ".join(filter(None, (obj.first_name, obj.last_name)))
        obj.full_name = joined or None
        obj.save(update_fields=["full_name"])


def make_name_field():
    return models.CharField(blank=True, max_length=50, null=True)


def make_nip_field():
    return models.CharField(
        blank=True,
        max_length=10,
        null=True,
        validators=[django.core.validators.RegexValidator(regex="^\\d{10}$")],
    )


class Migration(migrations.Migration):

    dependencies = [
        ("zetom", "0006_oferta_source_requestmain_source_requestnull_source_and_more"),
    ]

    operations = [
        migrations.AddField(model_name="oferta", name="first_name", field=make_name_field()),
        migrations.AddField(model_name="oferta", name="last_name", field=make_name_field()),
        migrations.AddField(model_name="requestmain", name="first_name", field=make_name_field()),
        migrations.AddField(model_name="requestmain", name="last_name", field=make_name_field()),
        migrations.AddField(model_name="requestnull", name="first_name", field=make_name_field()),
        migrations.AddField(model_name="requestnull", name="last_name", field=make_name_field()),
        migrations.AddField(model_name="wniosek", name="first_name", field=make_name_field()),
        migrations.AddField(model_name="wniosek", name="last_name", field=make_name_field()),
        migrations.AddField(model_name="zlecenie", name="first_name", field=make_name_field()),
        migrations.AddField(model_name="zlecenie", name="last_name", field=make_name_field()),

        migrations.RunPython(split_full_name, reverse_code=join_first_last),

        migrations.RemoveField(model_name="requestmain", name="full_name"),

        migrations.AlterField(model_name="oferta", name="company_nip", field=make_nip_field()),
        migrations.AlterField(model_name="requestmain", name="company_nip", field=make_nip_field()),
        migrations.AlterField(model_name="requestnull", name="company_nip", field=make_nip_field()),
        migrations.AlterField(model_name="wniosek", name="company_nip", field=make_nip_field()),
        migrations.AlterField(model_name="zlecenie", name="company_nip", field=make_nip_field()),
    ]
