# Generated by Django 5.2.13 on 2026-06-30 20:30
# claude: HistoricalRequestMain + RequestAttachment вынесены сюда из 0006.
# claude: их дописали в уже-применённую 0006 -> migrate её пропускал и таблицы не создавались.
# claude: на БД, где таблицы уже существуют, применять как `migrate --fake zetom 0007`.

import django.contrib.postgres.fields
import django.db.models.deletion
import phonenumber_field.modelfields
import simple_history.models
from django.conf import settings
from django.db import migrations, models

import crm.clients.validators


class Migration(migrations.Migration):

    dependencies = [
        ("zetom", "0006_alter_oferta_company_name_alter_oferta_created_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalRequestMain",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("phone", "Phone"),
                            ("email", "Email"),
                            ("site", "Site"),
                            ("main", "Parent"),
                            ("manual", "Manual"),
                            ("other", "Other"),
                        ],
                        default="other",
                        verbose_name="Source",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Updated at"
                    ),
                ),
                ("first_name", models.CharField(blank=True, max_length=50, null=True)),
                ("last_name", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None, verbose_name="Phone"
                    ),
                ),
                (
                    "company_name",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Company name",
                    ),
                ),
                ("email", models.EmailField(max_length=100, verbose_name="Email")),
                (
                    "company_nip",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        validators=[crm.clients.validators.validate_nip],
                    ),
                ),
                ("message", models.TextField(blank=True, null=True)),
                (
                    "departments",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("DEPARTMENT_0", "Research Team"),
                                ("DEPARTMENT_1", "Calibration Team"),
                                ("DEPARTMENT_2", "Length and Angle Lab"),
                                ("DEPARTMENT_3", "Electrical Lab"),
                                ("DEPARTMENT_4", "Mechanical Lab"),
                                ("DEPARTMENT_5", "Heating Equipment Lab"),
                                ("DEPARTMENT_6", "Technical Office"),
                            ],
                            max_length=30,
                        ),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("open", "Open"),
                            ("closed", "Closed"),
                            ("inactive", "Inactive"),
                            ("cancelled", "Cancelled"),
                            ("deleted", "Deleted"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("address", models.CharField(blank=True, max_length=228, null=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "from_null",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="zetom.requestnull",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Information",
                "verbose_name_plural": "historical Information",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="RequestAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="request_attachments/%Y/%m/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "request_main",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="zetom.requestmain",
                    ),
                ),
                (
                    "request_null",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="zetom.requestnull",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Attachment",
                "verbose_name_plural": "Attachments",
            },
        ),
    ]
