# Generated by Django 5.2.13 on 2026-07-01 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("zetom", "0007_historicalrequestmain_requestattachment"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeletedValidationRequest",
            fields=[],
            options={
                "verbose_name": "Deleted Validation Request",
                "verbose_name_plural": "Deleted Validation Requests",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("zetom.requestnull",),
        ),
    ]
