# Generated by Django 5.2.13 on 2026-05-08 16:05

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zetom", "0007_remove_requestmain_full_name_oferta_first_name_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="oferta",
            options={"verbose_name": "Offer", "verbose_name_plural": "Offers"},
        ),
        migrations.AlterModelOptions(
            name="wniosek",
            options={
                "verbose_name": "Application",
                "verbose_name_plural": "Applications",
            },
        ),
        migrations.AlterModelOptions(
            name="zlecenie",
            options={"verbose_name": "Order", "verbose_name_plural": "Orders"},
        ),
        migrations.AlterField(
            model_name="oferta",
            name="departments",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("DEPARTMENT_0", "Research Team"),
                        ("DEPARTMENT_1", "Calibration Team"),
                        ("DEPARTMENT_2", "Length and Angle Lab"),
                        ("DEPARTMENT_3", "Electrical Lab"),
                        ("DEPARTMENT_4", "Mechanical Lab"),
                        ("DEPARTMENT_5", "Heating Equipment Lab"),
                        ("DEPARTMENT_6", "Technical Office"),
                    ],
                    max_length=30,
                ),
                blank=True,
                default=list,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="requestmain",
            name="departments",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("DEPARTMENT_0", "Research Team"),
                        ("DEPARTMENT_1", "Calibration Team"),
                        ("DEPARTMENT_2", "Length and Angle Lab"),
                        ("DEPARTMENT_3", "Electrical Lab"),
                        ("DEPARTMENT_4", "Mechanical Lab"),
                        ("DEPARTMENT_5", "Heating Equipment Lab"),
                        ("DEPARTMENT_6", "Technical Office"),
                    ],
                    max_length=30,
                ),
                blank=True,
                default=list,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="requestnull",
            name="departments",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("DEPARTMENT_0", "Research Team"),
                        ("DEPARTMENT_1", "Calibration Team"),
                        ("DEPARTMENT_2", "Length and Angle Lab"),
                        ("DEPARTMENT_3", "Electrical Lab"),
                        ("DEPARTMENT_4", "Mechanical Lab"),
                        ("DEPARTMENT_5", "Heating Equipment Lab"),
                        ("DEPARTMENT_6", "Technical Office"),
                    ],
                    max_length=30,
                ),
                blank=True,
                default=list,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="wniosek",
            name="departments",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("DEPARTMENT_0", "Research Team"),
                        ("DEPARTMENT_1", "Calibration Team"),
                        ("DEPARTMENT_2", "Length and Angle Lab"),
                        ("DEPARTMENT_3", "Electrical Lab"),
                        ("DEPARTMENT_4", "Mechanical Lab"),
                        ("DEPARTMENT_5", "Heating Equipment Lab"),
                        ("DEPARTMENT_6", "Technical Office"),
                    ],
                    max_length=30,
                ),
                blank=True,
                default=list,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="zlecenie",
            name="departments",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("DEPARTMENT_0", "Research Team"),
                        ("DEPARTMENT_1", "Calibration Team"),
                        ("DEPARTMENT_2", "Length and Angle Lab"),
                        ("DEPARTMENT_3", "Electrical Lab"),
                        ("DEPARTMENT_4", "Mechanical Lab"),
                        ("DEPARTMENT_5", "Heating Equipment Lab"),
                        ("DEPARTMENT_6", "Technical Office"),
                    ],
                    max_length=30,
                ),
                blank=True,
                default=list,
                size=None,
            ),
        ),
    ]
