# Generated by Django 5.2.13 on 2026-07-01 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("zetom", "0008_deletedvalidationrequest"),
    ]

    operations = [
        migrations.CreateModel(
            name="CancelledValidationRequest",
            fields=[],
            options={
                "verbose_name": "Cancelled Validation Request",
                "verbose_name_plural": "Cancelled Validation Requests",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("zetom.requestnull",),
        ),
    ]
