# Generated by Django 5.2.13 on 2026-07-01 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zetom", "0009_cancelledvalidationrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="requestnull",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("open", "Open"),
                    ("closed", "Closed"),
                    ("inactive", "Inactive"),
                    ("cancelled", "Cancelled"),
                    ("deleted", "Deleted"),
                ],
                default="active",
                max_length=20,
            ),
        ),
    ]
