# Generated by Django 5.2.13 on 2026-07-14 13:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("zetom", "0010_requestnull_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StepNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "action",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="What was done"
                    ),
                ),
                ("text", models.TextField(verbose_name="Note")),
                (
                    "target_object_id",
                    models.PositiveIntegerField(verbose_name="Target object id"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="step_notes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Author",
                    ),
                ),
                (
                    "target_content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="step_notes",
                        to="contenttypes.contenttype",
                        verbose_name="Target content type",
                    ),
                ),
            ],
            options={
                "verbose_name": "Step note",
                "verbose_name_plural": "Step notes",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=[
                            "target_content_type",
                            "target_object_id",
                            "-created_at",
                        ],
                        name="zetom_stepn_target__73d68d_idx",
                    )
                ],
            },
        ),
    ]
