# Generated by Django 5.2.13 on 2026-07-14 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zetom", "0011_stepnote"),
    ]

    operations = [
        migrations.AddField(
            model_name="stepnote",
            name="next_contact_at",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="Next client contact at",
            ),
        ),
    ]
