# Generated by Django 5.2.13 on 2026-07-21 02:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0006_company_companypersonlink"),
        ("zetom", "0012_stepnote_next_contact_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalrequestmain",
            name="company",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="clients.company",
                verbose_name="Company",
            ),
        ),
        migrations.AddField(
            model_name="requestmain",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="requests",
                to="clients.company",
                verbose_name="Company",
            ),
        ),
    ]
