# Generated by Django 5.2.13 on 2026-08-24 02:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "clients",
            "0009_remove_client_client_type_remove_client_company_name_and_more",
        ),
        ("contenttypes", "0002_remove_content_type_name"),
        ("zetom", "0014_stepnote_reminder_sent_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="stepnote",
            name="channel",
            field=models.CharField(
                blank=True,
                choices=[
                    ("call", "Call"),
                    ("email", "Email"),
                    ("meeting", "Meeting"),
                    ("chat", "Chat"),
                    ("other", "Other"),
                ],
                max_length=20,
                verbose_name="Channel",
            ),
        ),
        migrations.AddField(
            model_name="stepnote",
            name="contact_person",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Contact person"
            ),
        ),
        migrations.AddField(
            model_name="stepnote",
            name="contacted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Contacted at"
            ),
        ),
        migrations.AddField(
            model_name="stepnote",
            name="done_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Done at"),
        ),
        migrations.AddField(
            model_name="stepnote",
            name="kind",
            field=models.CharField(
                choices=[("contact", "Contact"), ("reminder", "Reminder")],
                default="contact",
                max_length=20,
                verbose_name="Kind",
            ),
        ),
        migrations.AddField(
            model_name="stepnote",
            name="person",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="step_notes",
                to="clients.client",
                verbose_name="Person",
            ),
        ),
        migrations.AlterField(
            model_name="stepnote",
            name="target_content_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="step_notes",
                to="contenttypes.contenttype",
                verbose_name="Target content type",
            ),
        ),
        migrations.AlterField(
            model_name="stepnote",
            name="target_object_id",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Target object id"
            ),
        ),
        migrations.AlterField(
            model_name="stepnote",
            name="text",
            field=models.TextField(blank=True, verbose_name="Note"),
        ),
    ]
