# Generated by Django 5.2.13 on 2026-08-24 02:42

from django.db import migrations

# claude
from crm.zetom.services.step_notes import backfill_contact_kind


def backfill_forwards(apps, schema_editor):
    StepNote = apps.get_model("zetom", "StepNote")
    backfill_contact_kind(StepNote)


class Migration(migrations.Migration):

    dependencies = [
        ("zetom", "0015_stepnote_contact_fields"),
    ]

    operations = [
        migrations.RunPython(backfill_forwards, migrations.RunPython.noop),
    ]
