# Generated by Django 5.2.13 on 2026-08-24 02:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "clients",
            "0009_remove_client_client_type_remove_client_company_name_and_more",
        ),
        ("contenttypes", "0002_remove_content_type_name"),
        ("zetom", "0016_backfill_stepnote_kind"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="stepnote",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("kind", "contact"), _negated=True),
                    ("contacted_at__isnull", False),
                    _connector="OR",
                ),
                name="stepnote_contact_requires_contacted_at",
            ),
        ),
        migrations.AddConstraint(
            model_name="stepnote",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("kind", "reminder"), _negated=True),
                    ("next_contact_at__isnull", False),
                    _connector="OR",
                ),
                name="stepnote_reminder_requires_next_contact_at",
            ),
        ),
    ]
