# Generated by Django 5.2.13 on 2026-08-24 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zetom", "0017_stepnote_kind_constraints"),
    ]

    operations = [
        migrations.AddField(
            model_name="wniosek",
            name="from_zlecenie",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="wnioski",
                to="zetom.zlecenie",
                verbose_name="From order",
            ),
        ),
        migrations.AddField(
            model_name="zlecenie",
            name="from_oferta",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="zlecenia",
                to="zetom.oferta",
                verbose_name="From offer",
            ),
        ),
    ]
