# Generated by Django 5.2.15 on 2026-10-07 09:41

import crm.clients.validators
import django.contrib.postgres.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zetom", "0018_document_chain"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalrequestmain",
            name="company_nip",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                validators=[crm.clients.validators.validate_nip],
                verbose_name="Company NIP",
            ),
        ),
        migrations.AlterField(
            model_name="historicalrequestmain",
            name="departments",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("DEPARTMENT_0", "Research Team"),
                        ("DEPARTMENT_1", "Calibration Team"),
                        ("DEPARTMENT_2", "Length and Angle Lab"),
                        ("DEPARTMENT_3", "Electrical Lab"),
                        ("DEPARTMENT_4", "Mechanical Lab"),
                        ("DEPARTMENT_5", "Heating Equipment Lab"),
                        ("DEPARTMENT_6", "Technical Office"),
                    ],
                    max_length=30,
                ),
                blank=True,
                default=list,
                size=None,
                verbose_name="Departments",
            ),
        ),
        migrations.AlterField(
            model_name="oferta",
            name="assigned_to",
            field=models.ManyToManyField(
                blank=True,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Assigned to",
            ),
        ),
        migrations.AlterField(
            model_name="oferta",
            name="company_nip",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                validators=[crm.clients.validators.validate_nip],
                verbose_name="Company NIP",
            ),
        ),
        migrations.AlterField(
            model_name="oferta",
            name="departments",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("DEPARTMENT_0", "Research Team"),
                        ("DEPARTMENT_1", "Calibration Team"),
                        ("DEPARTMENT_2", "Length and Angle Lab"),
                        ("DEPARTMENT_3", "Electrical Lab"),
                        ("DEPARTMENT_4", "Mechanical Lab"),
                        ("DEPARTMENT_5", "Heating Equipment Lab"),
                        ("DEPARTMENT_6", "Technical Office"),
                    ],
                    max_length=30,
                ),
                blank=True,
                default=list,
                size=None,
                verbose_name="Departments",
            ),
        ),
        migrations.AlterField(
            model_name="oferta",
            name="notes",
            field=models.TextField(blank=True, null=True, verbose_name="Notes"),
        ),
        migrations.AlterField(
            model_name="oferta",
            name="price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Price",
            ),
        ),
        migrations.AlterField(
            model_name="requestmain",
            name="assigned_to",
            field=models.ManyToManyField(
                blank=True,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Assigned to",
            ),
        ),
        migrations.AlterField(
            model_name="requestmain",
            name="company_nip",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                validators=[crm.clients.validators.validate_nip],
                verbose_name="Company NIP",
            ),
        ),
        migrations.AlterField(
            model_name="requestmain",
            name="departments",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("DEPARTMENT_0", "Research Team"),
                        ("DEPARTMENT_1", "Calibration Team"),
                        ("DEPARTMENT_2", "Length and Angle Lab"),
                        ("DEPARTMENT_3", "Electrical Lab"),
                        ("DEPARTMENT_4", "Mechanical Lab"),
                        ("DEPARTMENT_5", "Heating Equipment Lab"),
                        ("DEPARTMENT_6", "Technical Office"),
                    ],
                    max_length=30,
                ),
                blank=True,
                default=list,
                size=None,
                verbose_name="Departments",
            ),
        ),
        migrations.AlterField(
            model_name="requestnull",
            name="assigned_to",
            field=models.ManyToManyField(
                blank=True,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Assigned to",
            ),
        ),
        migrations.AlterField(
            model_name="requestnull",
            name="company_nip",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                validators=[crm.clients.validators.validate_nip],
                verbose_name="Company NIP",
            ),
        ),
        migrations.AlterField(
            model_name="requestnull",
            name="departments",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("DEPARTMENT_0", "Research Team"),
                        ("DEPARTMENT_1", "Calibration Team"),
                        ("DEPARTMENT_2", "Length and Angle Lab"),
                        ("DEPARTMENT_3", "Electrical Lab"),
                        ("DEPARTMENT_4", "Mechanical Lab"),
                        ("DEPARTMENT_5", "Heating Equipment Lab"),
                        ("DEPARTMENT_6", "Technical Office"),
                    ],
                    max_length=30,
                ),
                blank=True,
                default=list,
                size=None,
                verbose_name="Departments",
            ),
        ),
        migrations.AlterField(
            model_name="wniosek",
            name="assigned_to",
            field=models.ManyToManyField(
                blank=True,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Assigned to",
            ),
        ),
        migrations.AlterField(
            model_name="wniosek",
            name="company_nip",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                validators=[crm.clients.validators.validate_nip],
                verbose_name="Company NIP",
            ),
        ),
        migrations.AlterField(
            model_name="wniosek",
            name="departments",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("DEPARTMENT_0", "Research Team"),
                        ("DEPARTMENT_1", "Calibration Team"),
                        ("DEPARTMENT_2", "Length and Angle Lab"),
                        ("DEPARTMENT_3", "Electrical Lab"),
                        ("DEPARTMENT_4", "Mechanical Lab"),
                        ("DEPARTMENT_5", "Heating Equipment Lab"),
                        ("DEPARTMENT_6", "Technical Office"),
                    ],
                    max_length=30,
                ),
                blank=True,
                default=list,
                size=None,
                verbose_name="Departments",
            ),
        ),
        migrations.AlterField(
            model_name="wniosek",
            name="notes",
            field=models.TextField(blank=True, null=True, verbose_name="Notes"),
        ),
        migrations.AlterField(
            model_name="zlecenie",
            name="assigned_to",
            field=models.ManyToManyField(
                blank=True,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Assigned to",
            ),
        ),
        migrations.AlterField(
            model_name="zlecenie",
            name="company_nip",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                validators=[crm.clients.validators.validate_nip],
                verbose_name="Company NIP",
            ),
        ),
        migrations.AlterField(
            model_name="zlecenie",
            name="departments",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("DEPARTMENT_0", "Research Team"),
                        ("DEPARTMENT_1", "Calibration Team"),
                        ("DEPARTMENT_2", "Length and Angle Lab"),
                        ("DEPARTMENT_3", "Electrical Lab"),
                        ("DEPARTMENT_4", "Mechanical Lab"),
                        ("DEPARTMENT_5", "Heating Equipment Lab"),
                        ("DEPARTMENT_6", "Technical Office"),
                    ],
                    max_length=30,
                ),
                blank=True,
                default=list,
                size=None,
                verbose_name="Departments",
            ),
        ),
        migrations.AlterField(
            model_name="zlecenie",
            name="notes",
            field=models.TextField(blank=True, null=True, verbose_name="Notes"),
        ),
        migrations.AlterField(
            model_name="zlecenie",
            name="price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Price",
            ),
        ),
    ]
