# Generated by Django 5.2.15 on 2026-10-07 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zetom", "0019_alter_historicalrequestmain_company_nip_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalrequestmain",
            name="address",
            field=models.CharField(
                blank=True, max_length=228, null=True, verbose_name="Address"
            ),
        ),
        migrations.AlterField(
            model_name="historicalrequestmain",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="First name"
            ),
        ),
        migrations.AlterField(
            model_name="historicalrequestmain",
            name="last_name",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Last name"
            ),
        ),
        migrations.AlterField(
            model_name="historicalrequestmain",
            name="message",
            field=models.TextField(blank=True, null=True, verbose_name="Message"),
        ),
        migrations.AlterField(
            model_name="oferta",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="First name"
            ),
        ),
        migrations.AlterField(
            model_name="oferta",
            name="last_name",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Last name"
            ),
        ),
        migrations.AlterField(
            model_name="oferta",
            name="message",
            field=models.TextField(blank=True, null=True, verbose_name="Message"),
        ),
        migrations.AlterField(
            model_name="requestmain",
            name="address",
            field=models.CharField(
                blank=True, max_length=228, null=True, verbose_name="Address"
            ),
        ),
        migrations.AlterField(
            model_name="requestmain",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="First name"
            ),
        ),
        migrations.AlterField(
            model_name="requestmain",
            name="last_name",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Last name"
            ),
        ),
        migrations.AlterField(
            model_name="requestmain",
            name="message",
            field=models.TextField(blank=True, null=True, verbose_name="Message"),
        ),
        migrations.AlterField(
            model_name="requestnull",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="First name"
            ),
        ),
        migrations.AlterField(
            model_name="requestnull",
            name="last_name",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Last name"
            ),
        ),
        migrations.AlterField(
            model_name="requestnull",
            name="message",
            field=models.TextField(blank=True, null=True, verbose_name="Message"),
        ),
        migrations.AlterField(
            model_name="wniosek",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="First name"
            ),
        ),
        migrations.AlterField(
            model_name="wniosek",
            name="last_name",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Last name"
            ),
        ),
        migrations.AlterField(
            model_name="wniosek",
            name="message",
            field=models.TextField(blank=True, null=True, verbose_name="Message"),
        ),
        migrations.AlterField(
            model_name="zlecenie",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="First name"
            ),
        ),
        migrations.AlterField(
            model_name="zlecenie",
            name="last_name",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Last name"
            ),
        ),
        migrations.AlterField(
            model_name="zlecenie",
            name="message",
            field=models.TextField(blank=True, null=True, verbose_name="Message"),
        ),
    ]
