# Generated by Django 5.2.15 on 2026-10-08 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zetom", "0020_alter_historicalrequestmain_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wniosek",
            name="application_number",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Application number"
            ),
        ),
        migrations.AlterField(
            model_name="zlecenie",
            name="deadline",
            field=models.DateField(blank=True, null=True, verbose_name="Deadline"),
        ),
    ]
