# Generated by Django 5.2.13 on 2026-04-27 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="department",
            field=models.CharField(
                blank=True,
                choices=[
                    ("DEPARTMENT_0", "department 1"),
                    ("DEPARTMENT_1", "department 2"),
                    ("DEPARTMENT_2", "department 3"),
                    ("DEPARTMENT_3", "department 4"),
                ],
                max_length=40,
                null=True,
            ),
        ),
    ]
