# Generated by Django 5.2.13 on 2026-05-04 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_userprofile_department"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="department",
            field=models.CharField(
                blank=True,
                choices=[
                    ("DEPARTMENT_0", "Zespół ds. Badań"),
                    ("DEPARTMENT_1", "Zespół ds. Wzorcowań"),
                    ("DEPARTMENT_2", "Pracownia Długości i Kąta"),
                    ("DEPARTMENT_3", "Pracownia Elektrotechniczna"),
                    ("DEPARTMENT_4", "Pracownia Mechaniczna"),
                    ("DEPARTMENT_5", "Pracownia Urządzeń Grzewczych"),
                    ("DEPARTMENT_6", "Biuro Techniczne"),
                ],
                max_length=40,
                null=True,
            ),
        ),
    ]
