# Generated by Django 5.2.13 on 2026-05-22 17:31

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_userprofile_job_title"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="department",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="departments",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("DEPARTMENT_0", "Research Team"),
                        ("DEPARTMENT_1", "Calibration Team"),
                        ("DEPARTMENT_2", "Length and Angle Lab"),
                        ("DEPARTMENT_3", "Electrical Lab"),
                        ("DEPARTMENT_4", "Mechanical Lab"),
                        ("DEPARTMENT_5", "Heating Equipment Lab"),
                        ("DEPARTMENT_6", "Technical Office"),
                    ],
                    max_length=30,
                ),
                blank=True,
                default=list,
                size=None,
            ),
        ),
    ]
