# Generated by Django 5.2.13 on 2026-05-25 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_userprofile_head_of_departments"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="extra_permissions",
            field=models.ManyToManyField(
                blank=True, related_name="extra_users", to="users.permission"
            ),
        ),
    ]
