# Generated by Django 5.2.13 on 2026-05-31 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_userprofile_extra_permissions"),
    ]

    operations = [
        migrations.AddField(
            model_name="permission",
            name="category",
            field=models.CharField(default="system", max_length=100),
        ),
    ]
