# Generated by Django 5.2.13 on 2026-06-29 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_permission_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="permission",
            name="category",
            field=models.CharField(
                default="system", max_length=100, verbose_name="Category"
            ),
        ),
        migrations.AlterField(
            model_name="permission",
            name="code",
            field=models.CharField(max_length=100, unique=True, verbose_name="Code"),
        ),
        migrations.AlterField(
            model_name="permission",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="role",
            name="code",
            field=models.CharField(max_length=50, unique=True, verbose_name="Code"),
        ),
        migrations.AlterField(
            model_name="role",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="role",
            name="permissions",
            field=models.ManyToManyField(
                blank=True, to="users.permission", verbose_name="Permissions"
            ),
        ),
    ]
