# Generated by Django 5.2.13 on 2026-08-01 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_alter_permission_category_alter_permission_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="otp_required",
            field=models.BooleanField(
                default=False,
                help_text="If enabled, the user must configure 2FA to access the admin panel.",
                verbose_name="2FA required",
            ),
        ),
    ]
