# Generated by Django 5.2.13 on 2026-08-04 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_userprofile_otp_required"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="otp_required",
        ),
    ]
