# Generated by Django 5.2.13 on 2026-08-22 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_userprofile_otp_exempt_trusteddevice"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="avatar",
            field=models.ImageField(
                blank=True, null=True, upload_to="avatars/", verbose_name="Avatar"
            ),
        ),
    ]
