# Generated by Django 5.2.15 on 2026-10-07 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0012_userprofile_avatar"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="permission",
            options={
                "verbose_name": "Permission",
                "verbose_name_plural": "Permissions",
            },
        ),
        migrations.AlterModelOptions(
            name="role",
            options={"verbose_name": "Role", "verbose_name_plural": "Roles"},
        ),
    ]
