# Generated by Django 5.2.15 on 2026-10-08 06:20

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0013_alter_permission_options_alter_role_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userprofile",
            options={
                "verbose_name": "User profile",
                "verbose_name_plural": "User profiles",
            },
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="departments",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("DEPARTMENT_0", "Research Team"),
                        ("DEPARTMENT_1", "Calibration Team"),
                        ("DEPARTMENT_2", "Length and Angle Lab"),
                        ("DEPARTMENT_3", "Electrical Lab"),
                        ("DEPARTMENT_4", "Mechanical Lab"),
                        ("DEPARTMENT_5", "Heating Equipment Lab"),
                        ("DEPARTMENT_6", "Technical Office"),
                    ],
                    max_length=30,
                ),
                blank=True,
                default=list,
                size=None,
                verbose_name="Departments",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="extra_permissions",
            field=models.ManyToManyField(
                blank=True,
                related_name="extra_users",
                to="users.permission",
                verbose_name="Extra permissions",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="head_of_departments",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("DEPARTMENT_0", "Research Team"),
                        ("DEPARTMENT_1", "Calibration Team"),
                        ("DEPARTMENT_2", "Length and Angle Lab"),
                        ("DEPARTMENT_3", "Electrical Lab"),
                        ("DEPARTMENT_4", "Mechanical Lab"),
                        ("DEPARTMENT_5", "Heating Equipment Lab"),
                        ("DEPARTMENT_6", "Technical Office"),
                    ],
                    max_length=30,
                ),
                blank=True,
                default=list,
                size=None,
                verbose_name="Head of departments",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="job_title",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Job title"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="main_departments",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("DEPARTMENT_0", "Research Team"),
                        ("DEPARTMENT_1", "Calibration Team"),
                        ("DEPARTMENT_2", "Length and Angle Lab"),
                        ("DEPARTMENT_3", "Electrical Lab"),
                        ("DEPARTMENT_4", "Mechanical Lab"),
                        ("DEPARTMENT_5", "Heating Equipment Lab"),
                        ("DEPARTMENT_6", "Technical Office"),
                    ],
                    max_length=30,
                ),
                blank=True,
                default=list,
                size=None,
                verbose_name="Main departments",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="users.role",
                verbose_name="Role",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
    ]
