# Generated by Django 5.2.13 on 2026-06-29 18:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("notification", "0002_remove_emailnotification_content_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailnotification",
            name="actor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sent_emails",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Actor",
            ),
        ),
        migrations.AlterField(
            model_name="emailnotification",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
        ),
        migrations.AlterField(
            model_name="emailnotification",
            name="payload",
            field=models.JSONField(default=dict, verbose_name="Payload"),
        ),
        migrations.AlterField(
            model_name="emailnotification",
            name="recipient_email",
            field=models.EmailField(max_length=254, verbose_name="Recipient email"),
        ),
        migrations.AlterField(
            model_name="emailnotification",
            name="sent_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Sent at"),
        ),
        migrations.AlterField(
            model_name="emailnotification",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("SENT", "Sent"),
                    ("FAILED", "Failed"),
                ],
                default="PENDING",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="emailnotification",
            name="status_reason",
            field=models.TextField(blank=True, null=True, verbose_name="Status reason"),
        ),
        migrations.AlterField(
            model_name="emailnotification",
            name="subject",
            field=models.CharField(max_length=255, verbose_name="Subject"),
        ),
        migrations.AlterField(
            model_name="emailnotification",
            name="template_name",
            field=models.CharField(max_length=255, verbose_name="Template name"),
        ),
        migrations.AlterField(
            model_name="notification",
            name="actor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="acted_inapp_notifications",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Actor",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
        ),
        migrations.AlterField(
            model_name="notification",
            name="is_read",
            field=models.BooleanField(default=False, verbose_name="Is read"),
        ),
        migrations.AlterField(
            model_name="notification",
            name="kind",
            field=models.CharField(
                choices=[
                    ("STATUS_CHANGE", "Status change"),
                    ("REVIEW_REQUEST", "Review request"),
                    ("REVIEW_RESOLVED", "Review resolved"),
                    ("ASSIGNMENT", "Assignment"),
                    ("SYSTEM", "System"),
                ],
                max_length=32,
                verbose_name="Kind",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="payload",
            field=models.JSONField(
                default=dict,
                help_text="Data to replace template placeholders.",
                verbose_name="Payload",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="read_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Read at"),
        ),
        migrations.AlterField(
            model_name="notification",
            name="recipient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inapp_notifications",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Recipient",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="target_content_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="contenttypes.contenttype",
                verbose_name="Target content type",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="target_object_id",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Target object id"
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="template_name",
            field=models.CharField(max_length=255, verbose_name="Template name"),
        ),
    ]
