# Generated by Django 5.2.15 on 2026-10-07 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notification", "0003_alter_emailnotification_actor_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="emailnotification",
            options={
                "verbose_name": "Email notification",
                "verbose_name_plural": "Email notifications",
            },
        ),
        migrations.AlterModelOptions(
            name="notification",
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
            },
        ),
    ]
